# QBIO 401: Introduction to Computational Analysis of Biological Data 

# Introduction to Python III
## 1. Work with data
### 1.1. Read files
#### *Create a File object*

In [82]:
File1=open("file_example.txt","r")

# File attribute
print(File1.name)
print(File1.mode)

# File methods
file_content=File1.read()
print(File1.read())
File1.close()

file_example.txt
r
This is line 1
This is line 2
This is line 3



#### *With statement*

In [16]:
with open("file_example.txt","r") as File1:
    file_stuff=File1.read()
    print(file_stuff)

This is line 1
This is line 2
This is line 3



#### *Read one line at a time*

In [6]:
with open("file_example.txt","r") as File1:
    file_stuff=File1.readline()
    print(file_stuff)

This is line 1



In [7]:
with open("file_example.txt","r") as File1:
    file_stuff=File1.readline()
    print(file_stuff)
    file_stuff=File1.readline()
    print(file_stuff)

This is line 1

This is line 2



In [8]:
with open("file_example.txt","r") as File1:
    for line in File1:
        print(line)

This is line 1

This is line 2

This is line 3


In [83]:
lines=[]
with open("file_example.txt","r") as File1:
    for line in File1:
        lines.append(line)
print(lines)        

['This is line 1\n', 'This is line 2\n', 'This is line 3\n']


### 1.2 Write files

In [11]:
with open("file_example.txt", "w") as File1:   
    File1.write("This is line 1\n")
    File1.write("This is line 2\n") 

Write Strings in a Line into a file

In [15]:
Lines=["This is line 1\n","This is line 2\n","This is line 3\n"]
with open("file_example.txt", "w") as File1:
    for line in Lines:
        File1.write(line)

## 2. Pandas

Libraries are pre-written code to help solve problem. Pandas is a popular library for data analysis. Pandas provides us with some powerful objects like DataFrames and Series which are very useful for working with and analyzing data.

In [104]:
data=[["A",1],["B",3],["C",5],["D",7]]

# Convention way
total=0
for i in data:
    total=total+i[1]
print(total)

# Pandas' way
import pandas as pd
df=pd.DataFrame(data)
print(df)
print(df.sum(0))
print(df.mean(0))


16
   0  1
0  A  1
1  B  3
2  C  5
3  D  7
0    ABCD
1      16
dtype: object
1    4.0
dtype: float64


In [110]:
import pandas as pd
csv_path="pandas_example.csv"
df=pd.read_csv(csv_path)
df

section         id                                               name  unit
0  12951R   QBIO 401  Introduction to Computational Analysis of Biol...   4.0
1  29253R   QBIO 430     Principles and Applications of Systems Biology   4.0
2  13481R   QBIO 481     Structural Bioinformatics: From Atoms to Cells   4.0
3  12990D  QBIO 490x                                  Directed Research   8.0
4  12993D   QBIO 493                Quantitative Biology Honors Seminar   2.0
5  12970D   QBIO 590                                  Directed Research   1.0

In [111]:
df.head()

section         id                                               name  unit
0  12951R   QBIO 401  Introduction to Computational Analysis of Biol...   4.0
1  29253R   QBIO 430     Principles and Applications of Systems Biology   4.0
2  13481R   QBIO 481     Structural Bioinformatics: From Atoms to Cells   4.0
3  12990D  QBIO 490x                                  Directed Research   8.0
4  12993D   QBIO 493                Quantitative Biology Honors Seminar   2.0

In [112]:
df.tail(2)

section        id                                 name  unit
4  12993D  QBIO 493  Quantitative Biology Honors Seminar   2.0
5  12970D  QBIO 590                    Directed Research   1.0

In [116]:
print(df['unit'].mean())
print(df['unit'].std())

3.8333333333333335
2.401388487243717


In [34]:
df[['section','unit']]

section  unit
0  12951R   4.0
1  29253R   4.0
2  13481R   4.0
3  12990D   8.0
4  12993D   2.0
5  12970D   1.0

In [129]:
df.loc[1:2:2,'name']

1    Principles and Applications of Systems Biology
Name: name, dtype: object

#### *Convertiton*

In [125]:
list1=df.values.tolist()
list1
dic1=df.to_dict()
dic1
a = pd.DataFrame(dic1)
a

section         id                                               name  unit
0  12951R   QBIO 401  Introduction to Computational Analysis of Biol...   4.0
1  29253R   QBIO 430     Principles and Applications of Systems Biology   4.0
2  13481R   QBIO 481     Structural Bioinformatics: From Atoms to Cells   4.0
3  12990D  QBIO 490x                                  Directed Research   8.0
4  12993D   QBIO 493                Quantitative Biology Honors Seminar   2.0
5  12970D   QBIO 590                                  Directed Research   1.0

## 3. Numpy 

Numpy is a library for scientific computing. Numpy provides objects for multi-dimensional arrays. It has many useful functions. There are many other advantages like speed and memory. Numpy is also the basis for pandas.

A numpy array is similar to a list. It's usually fixed in size and each element is of the same type.

In [35]:
# Import numpy package
import numpy as np

# Create a numpy array from a List
a = np.array([0,1,2,3,4])

# Access an element in a numpy array
print("a[0]:",a[0])
print("a[1]:",a[1])

a[0]: 0
a[1]: 1


#### *Assign value*

In [39]:
a=np.array([3.1, 11.02, 6.2, 213.2, 5.2])
print(b)
a[0]=100
print(b)

[  3.1   11.02   6.2  213.2    5.2 ]
[100.    11.02   6.2  213.2    5.2 ]


#### *Slicing*

In [42]:
a=np.array([3.1, 11.02, 6.2, 213.2, 5.2])
b=a[0:3:2]
b

array([3.1, 6.2])

#### *Numpy Attributes*

In [45]:
a=np.array([3.1, 11.02, 6.2, 213.2, 5.2])
print("a.size:",a.size)
print("a.ndim:",a.ndim)
print("a.shape:",a.shape)

a.size: 5
a.ndim: 1
a.shape: (5,)


#### *Numpy methods*

In [49]:
a=np.array([3.1, 11.02, 6.2, 213.2, 5.2])
print("a.mean():",a.mean())
print("a.std():",a.std())
print("a.max():",a.max())
print("a.min():",a.min())

a.mean(): 47.74399999999999
a.std(): 82.76874134599365
a.max(): 213.2
a.min(): 3.1


#### *Numpy array operations*
Addition

In [53]:
u = np.array([1, 0])
v = np.array([0, 1])
z=u+v
z

array([1, 1])

Multiplication

In [55]:
y = np.array([1, 2])
z=y*2
z

array([2, 4])

Product of two numpy array

In [57]:
u = np.array([1, 2])
v = np.array([3, 2])
z=u*v
z

array([3, 4])

Dot product

In [59]:
u = np.array([1, 2])
v = np.array([3, 2])
np.dot(u, v)

7

Add a constant

In [60]:
u = np.array([1, 2])
u+1

array([2, 3])

Mathematical functions

In [63]:
print("np.pi:",np.pi)

u = np.array([1, 2])
print("np.sin(u):",np.sin(u))

np.pi: 3.141592653589793
np.sin(u): [0.84147098 0.90929743]


## 2D array

In [64]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

Numpy attribute

In [68]:
b=np.array(a)
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
2
(3, 3)
9


Access elements in numpy array

In [71]:
print("a[0][0]:",a[0][0])
print("a[0][0:2]:",a[0][0:2])

a[0][0]: 11
a[0][0:2]: [11, 12]


Basic operation

In [75]:
X = np.array([[1, 0], [0, 1]]) 
Y = np.array([[2, 1], [1, 2]]) 
print("X:",X)
print("Y:",Y)

X: [[1 0]
 [0 1]]
Y: [[2 1]
 [1 2]]


Addition

In [76]:
Z=X+Y
Z

array([[3, 1],
       [1, 3]])

Multiplication

In [77]:
Y = np.array([[2, 1], [1, 2]]) 
print("Y:",Y)
Z = 2 * Y
print("Z:",Z)

Y: [[2 1]
 [1 2]]
Z: [[4 2]
 [2 4]]


Element-wise product

In [130]:
X*Y

array([[2, 0],
       [0, 2]])

Dot product

In [133]:
A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])
Z=np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [135]:
C = np.array([[1,1],[2,2],[3,3]])
print(C)
print(C.T)

[[1 1]
 [2 2]
 [3 3]]
[[1 2 3]
 [1 2 3]]
