## Nichollas Tidow
## QBIO 401
## September 16, 2020
## HW 04

### Function 01 
#### Write Python function that takes five inputs: [8pt]
##### 1. A DNA sequence string X,
##### 2. A DNA sequence string Y,
##### 3. A score Smatch occurs for matching the characters of X and Y,
##### 4. A penalty Pmismatch occurs for mismatching the characters of X and Y
##### 5. A penalty Pgap occurs if a gap is inserted into the string.
#### This function returns a Dynamic Programming scoring matrix for the global pairwise alignment.

In [2]:
# importing numpy module
import numpy as np 

# Name: dynamicMatrix
# Purpose: create a dynamic programming matrix for global pairwise aligment of 2 sequences
# Input: DNA sequence X, DNA sequence Y, sMatch score when the bases match, sMismatch penalty when bases mismatch, and a pGap penalty when there is a gap inserted
# Output: a numpy array dynamic scoring matrix 
def dynamicMatrix(X,Y,sMatch,pMismatch,pGap):
    # initialize scoring matrix using a numpy array with lengths of sequences 
    dp_matrix = np.ndarray(shape=(len(X)+1,len(Y)+1),dtype=int)
    # fill matrix w/ 0s
    dp_matrix.fill(0)
    
    # Iterate over sequence X to add the gap border
    for i in range(len(X)+1):
        # multiply gap value times index position
        dp_matrix[i][0] = pGap*i
        
    # Iterate over sequence X to add the gap border
    for j in range(len(Y)+1):
        # multiply gap value times index position
        dp_matrix[0][j] = pGap*j
        
    # for loop itereration over sequences starting a index 1 and stopping at length of sequence + 1
    for i in range(1,len(X)+1):
        # same for loop iteration but for the other sequence
        for j in range(1,len(Y)+1):
            # intialize scoring list
            scores = [0,0,0]  
            # if 0 index of X and 0 index of Y are equal
            if X[i-1] == Y[j-1]:
                # Score diagonal match 
                # sMatch value + the diagonal index value
                # place that sum in index 1 of scores
                scores[1] = sMatch + dp_matrix[i-1][j-1]
            # else the scores result in a mismatch
            else:
                # Score diagonal mismatch
                # sMatch value + the diagonal index value
                # place that sum in index 1 of scores
                scores[1] = pMismatch + dp_matrix[i-1][j-1]   
            # Score left
            # pGap value + the left index value
            # place that sum in index 0 of scores
            scores[0] = pGap + dp_matrix[i][j-1]
            # Score up
            # pGap value + the up index value
            # place that sum in index 2 of scores
            scores[2] = pGap + dp_matrix[i-1][j]
            # Select the max value of the scores list
            best = max(scores)
            # add the max values to the matrix
            dp_matrix[i,j]= best
            
    # Print title of matrix        
    print("Dynamic Programming Matrix")       
    # Return the matrix
    return dp_matrix

In [3]:
print(dynamicMatrix("ACGA", "CACT", 3, -1, -2))

Dynamic Programming Matrix
[[ 0 -2 -4 -6 -8]
 [-2 -1  1 -1 -3]
 [-4  1 -1  4  2]
 [-6 -1  0  2  3]
 [-8 -3  2  0  1]]


In [4]:
# Back storing Bonus from discussion
import numpy as np
def backStore(X,Y,sMatch,pMismatch,pGap):
    f = np.zeros(len(X)+1, len(Y)+1))
    f[:] = np.nan
    f[0,0] = 0
    def check(i,j):
        if not np.isnan(f[i,j]):
            return f[i,j]
        if i>0 and j>0:
            diagonalS= check(i-1, j-1) + (sMatch if X[i-1]==Y[j-1] else pMismatch)
        else:
            diagonalS = -np.inf
        if i>0:
            gapS = max(gapS, check(i-1,j)+ pGap)
        if j>0:
            gapS = max(gapS, check(i,j-1)+ pGap)
        f[i,j] = max(diagonalS,gapS)
        
                
    


SyntaxError: unmatched ')' (<ipython-input-4-cabd6f9a47e1>, line 4)

In [9]:
# intro for next homework using classes using OOP
class student:
    def __init__(self,name,stud_id):
        self.name = name
        self.id = stud_id
    def print(self):
        print("Name: %s ID: %s\n" % (self.name, self.id))
        
        
        

In [11]:
a = student("A","1000")
a.print()

Name: A ID: 1000



In [28]:
# defining a lise
class Node:
    def __init__(self,value):
        self.value = value
        self.next = None
        
# Node1 -> Node2 -> Node3 -> Node4 -> ... -> None
# defining a tree structure
class TreeNode:
    def __init__(self,value):
        self.value = value
        self.left = None
        self.right = None
    def print(self):
        print("Node value: %d\n", self.value)
        if self.left is not None: 
            self.left.print()
        if self.right is not None: 
            self.right.print()
        


In [29]:
a = TreeNode(1)
b = TreeNode(2)
a.left =b
c = TreeNode(3)
a.right = c
d = TreeNode(4)
c.right = d
e = TreeNode(5)
b.right = e

In [30]:
a.print()

AttributeError: 'TreeNode' object has no attribute 'value'